### ISSUE TITLE
TLS Error when following fpki-graph URL

### ISSUE THREAD

**Issue by grandamp** [GSA/fpki-guides#141]
#### Description of Issue: ####
Follow link to: https://fpki-graph.fpki-lab.gov/crawler/
Error received: "Privacy Error" and "NET:ERR_CERT_AUTHORITY_INVALID" in Chrome

**Comment by grandamp** [comment]
![screenshot_20171010-132439](https://user-images.githubusercontent.com/13126304/31401056-9fa8232a-adbf-11e7-96dc-dafe35d5f292.png)

Screenshot on Android 8.0.0

**Comment by indrajit-gsa** [comment]
@grandamp Does the advanced setting allow you to accept and store the cert chain? My android phone seems to be fine with the IdenTrust certs.

**Comment by lachellel** [comment]
1. The fpki crawler isn't serving the intermediate CA cert(s) from the server...
2. When you fetch the AIA to find the issuer/intermediate and root - it only builds a certificate path to Common Policy CA.
3.  There is a certificate path to another **public trust Identrust root** that you can't directly find from the AIA.  I don't want to state it's "unpublished" - but the issuer/intermediate is not published in the AIA stated in the end entity cert.  I _think_ you can find it via SIA from that Identrust root _down_.   

The relevant points are: 

- We don't want consumers to get these error in the first place in general for any *.gov **federal** websites.  
- For mobile / android / chrome - the servers (etc) need to serve the full chain to a public trust root.  https://https.cio.gov/technical-guidelines/#a-complete-certificate-chain

When the site got a new cert in August, it looks like the installation didn't include the intermediates.  OR, the site is being used to test "untrusted" (deliberate).

**Comment by grandamp** [comment]
I'm running Android 8 on a Pixel.  Importing CA certificates manually has historically yielded a persistent system notification, warning "network may be monitored", so manually adding is infeasible, and not recommended.

I.e., https://issuetracker.google.com/issues/36984301

**Comment by weirdscience** [comment]
@lachellel is correct. One of the intermediates did not make it in the chain after the new certificate was loaded. It should be fixed now.

I will also follow-up with the vendor to include the intermediate in the AIA. IdenTrust has a split trust path with the FPKI. IdenTrust ACES are trusted by both the FPKI and Mozilla through the IdenTrust Public Sector Root CA. The IdenTrust ACES CA 2 is not cross-certified with the FPKI. IdenTrust ACES certificates can validate to the Federal Common Policy through the Federal Bridge. FPKI certificates cannot validate back to the IdenTrust Public Root because there is no cross-certificate. DigiCert has a similar hierarchy.

![identrust aces](https://user-images.githubusercontent.com/7793270/31421724-0ea8e1fe-ae17-11e7-9e53-120d39c7c425.PNG)

**Comment by grandamp** [comment]
LGTM, thanks!
