### ISSUE TITLE
Add Hot Topics Page To Address Microsoft Trust Store and Google Certificate Transparency (CT) Changes

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#168]
#### Description of Issue: ####
Microsoft and Google are making changes in IE/Edge and Chrome which will impact the FPKI. This hot topic page will outline the challenge and provide recommended solutions to lessen the impact.

#### If a New Page or Content is Needed, Expected Outcomes: ####
New page with new content.

**Comment by indrajit-gsa** [comment]
@lachellel -- Is the navigation for these hot topics going to be "Announcements"? Should we make it a collection in a new directory which will auto update the menu when new files are added?

**Comment by lachellel** [comment]
I notionally added "announcement" in the front matter for the markdown.  I didn't add it as a category yet - see the question in the original PR #169 

@weirdscience - what do you think?
@djpackham - would annoucements make sense in the navigation?  Or hot topics?

**Comment by weirdscience** [comment]
@weirdscience do we need the full email / announcement? Or only the option 1 info and FAQ, and then we'll add the configuration steps?

- I reproduced the email info so not needed unless I missed something. I haven't received feedback on the configuration steps to add it back in.

Looks good to me.

**Comment by weirdscience** [comment]
For the Chrome announcement, would it be more helpful to have specific instructions on how to turn off CT or should we point to the KB? http://www.chromium.org/administrators/policy-list-3#CertificateTransparencyEnforcementDisabledForUrls

**Comment by clstmbrly** [comment]
@lachellel @weirdscience I created a 168-hot-topics branch in GSA/FPKI-Guides.  Both MS and Google Hot Topic files are under /_Pages.  
The edited, current version of the Microsoft Hot Topic is here:
[https://github.com/GSA/fpki-guides/blob/168-hot-topics/pages/fpki_hottopic_microsoftconstraint.md](url)
Still some information that needs to be supplied there ("TBD" and Option 2 steps).
Currently working on the Google Hot Topic.

**Comment by djpackham** [comment]
IMO, I'd go with "Announcements". Would it make sense to modify the landing page to include the titles of the announcements with links? Or make the landing page the announcements page?

**Comment by clstmbrly** [comment]
My .02 cents:  Introduction is a good landing page as is. IMHO, "Announcements" wouldn't work there. “Announcements” could be just before or just after “Introduction” on the sidebar navigation. (Or just before “System Notifications,” but folks might not see it there quickly.)
How about this for the sidebar nav:  
Announcements (top level)
+ Microsoft Policy Changes (2nd level) (not catchy words, but needs to be short)
+ Google Policy Changes (2nd level)

**Comment by indrajit-gsa** [comment]
I was also thinking similar to @djpackham suggestion about making the announcements index page to contain links to each page with new announcements at the top. I will see if I can code that to loop through the files and pick the title, or for now, just hard code it.

So it will be something like below (taking the suggestions from @clstmbrly)
- ...
- Trust Stores
- Useful Tools +
- Announcements +
   - Microsoft Policy Changes
   - Google Policy Changes
- System Notifications
- ...

Assuming that you all are fine with the left navigation title 'Announcements' (my preference as well), I can make the required changes. Let me know if any of you have other thoughts.

**Comment by lachellel** [comment]
Announcements sound good.  

Since we're making the announcements a collection (similar to the other playbooks), then the announcements landing page markdown can loop through and list (and link) to the sub-pages.  It doesn't need custom or hard-coding.   

https://jekyllrb.com/docs/collections/
{% for item in site.\<collectionname> %}

(etc)

Here are the steps to do first, so we can build locally and in federalist without stepping on each other: 

- Create the new folder (for the collection)
- Move the draft markdowns (google and microsoft announcements) into this folder
- Update the draft markdown front matter to specify the collection name
- Update the config.yml to add the navigation and collection reference
- Commit 

:+1:

**Comment by indrajit-gsa** [comment]
I made the following updates:
- Moved the 2 files to _announcements folder.
- Made necessary changes to collections in config.yml.
- Added description to each announcement file header. This will show on the index page.
- Added publish date to each announcement file header. This will show on the index page and on each announcement page. Made necessary change to layout file.
- The announcement index page will display the title, publish date and description in reverse order (new announcements on top). Possibly we can make the same reverse order for the left navigation to render new items at top, or eliminate displaying the items in navigation since this list will grow with time.
- Used the navtitle header to display shorter navigation title on the left menu.

I have pushed the changes to the branch. You can preview here - https://federalist-proxy.app.cloud.gov/preview/gsa/fpki-guides/168-hot-topics/announcements/

Note: the individual announcement files have not rendered yet in this preview site (404 error), but if you try in your local instance, it will generate.

The contents for each announcement need additional detail. Please help @clstmbrly with the content edits. She has added coder comments (view markdown).

**Comment by clstmbrly** [comment]
@weirdscience @lachellel  The edited, current version of the Google Announcement is here:  
https://github.com/GSA/fpki-guides/edit/168-hot-topics/_announcements/02_google_ct.md 

I added "coder" comments for questions that came up when I read the announcement.  
For example:  Google's use of CT introduces what problem for the FPKI? 
Please take a look at the Markdown mark-up view to see these.
There are also still some placeholders in the file where text needs to be added.

Be glad to make any changes that you want.

**Comment by indrajit-gsa** [comment]
I found this link (https://transparencyreport.google.com/https/certificates) for verifying the CT status for any existing website. It may be helpful to add this to the Google CT topic.

**Comment by lachellel** [comment]
Not needed - it's a red herring for the purposes of the announcement.  I can assert that not a single federal CA in FPKI (i.e. the service providers) include CT by default.  The focus of the announcement is in regards to our federal root and federal CAs, and the impacts which will be primarily to the **intranets**.

**Comment by clstmbrly** [comment]
@lachellel Ken had a few more changes to both Hot Topics.  Will resubmit shortly.

**Comment by clstmbrly** [comment]
@lachellel The latest changes have been incorporated. The Hot Topics announcements are ready for your review.  Have a lovely evening:-).

**Comment by lachellel** [comment]
@weirdscience @djpackham 

I just made some modifications to the microsoft removal of ssl trust hot topic.  We stated three different trust stores (Trusted Roots, Enterprise, and NTAuth) in the instructions in different places.  I think this is due to copying from piv (ntauth).  

We need to push Common to Enterprise Trust, correct?  NTAuth is irrelevant, and I'm wavering between Trusted Roots and Enterprise ...

**Comment by clstmbrly** [comment]
@lachellel As one of the latest changes, Ken instructed me to change all related uses of "Enterprise" to NTAuth.  Also said COMMON is installed to NTAuth.  

We refer to Trusted Root in terms of "Microsoft Trusted Root Program," which is what Microsoft really calls its Trust Store program--the term we used previously.  Verified this on Microsoft site.  Changed the Microsoft program references for correctness.

Also, he suggested that since we say "TLS trust bit," I should change all "SSL certificates" to "TLS certificates."  I thought maybe "TLS/SSL certificates."  Previously, we used the term, "server authentication certificates."

Please let me know about Enterprise and NTAuth and any other changes you'd like made.

**Comment by clstmbrly** [comment]
@lachellel I see we were working in the file at the same time.

**Comment by weirdscience** [comment]
@lachellel if you send a link to the version you have, it will help with context. I'm looking at this copy https://federalist-proxy.app.cloud.gov/preview/gsa/fpki-guides/168-hot-topics/announcements/mspkichanges/

1) Three different trust stores (Trusted Roots, Enterprise, and NTAuth) - I see we use Trusted Roots to refer to Microsoft Trusted Root Program and the specific directory in the MMC "Trusted Root Certification Authority". Both of those are correct terms for either program or folder directory and match Microsoft instructions for adding a root CA by GPO.

I see enterprise trust store in the FAQ section so we went with the questionee terms. 
@clstmbrly - If LaChelle hasn't made the change, make a global change from "Enterprise Trust Store" to "Enterprise NTAuth Store". That is actually what it is called. Just don't change it in the CertUtil command line examples the correct terms are NTAuthCA and NTAuth for those two specific lines.

That should solve the discrepancy between "Enterprise Trust Store" and NTAuth.

**Comment by djpackham** [comment]
I had a few separate discussions and I think we're on the same page that NTAuth isn't the right store to add COMMON.

IMO, I believe it is between the Enterprise Trust store and Trusted Root Certification Authorities store. I found this article that provides a brief description of the difference between Enterprise Trust store and the Trusted Root Certification Authorities store:

- https://technet.microsoft.com/en-us/library/cc700805.aspx

@weirdscience mentioned he'd contact Microsoft to see if they have any comment on the CTL process in relation to the Trust Root Certification Authority store. I'm still looking to see what the best store is to use.

**Comment by lachellel** [comment]
@clstmbrly @weirdscience @djpackham 

Added changes for the microsoft announcement.  It's on preview: https://federalist-proxy.app.cloud.gov/preview/gsa/fpki-guides/168-hot-topics/announcements/

Changes:
- the difference between the physical and the logical trust stores seems to cause confusion (in words and configs)
- I explicitly added a short FAQ on this
- Removed the step by step instructions and added helpful hints instead
- Changed answers to some of the questions already submitted (FAQ)

For **clients** - tested on:

- Windows 7 + IE 11 + Chrome 64
- Windows 10 + Edge

I have not tested on the mobile platforms. 

We should add a testing section to show how to test today and how to test when the pre-prod CTL is provided by Microsoft.  However, the addition of a testing section can wait - we need to get the link out earlier rather than later!

**Comment by clstmbrly** [comment]
@lachellel I sent some editorial glitches to your email.  @djpackham

**Comment by weirdscience** [comment]
I added a pull request #186 to start a testing procedure outline.
