### ISSUE TITLE
Disable scroll behavior on FPKI graph

### ISSUE THREAD

**Issue by konklone** [GSA/fpki-guides#204]
The [FPKI Graph](https://fpki.idmanagement.gov/tools/fpkigraph/) is awesome. However, scrolling down the page causes the graph to scroll wildly out (or in) if the cursor is positioned over the chart as you scroll up and down.

I observed this behavior on a Macbook Pro using the trackpad, though I assume it also affects mouse scroll-wheel users.

**Comment by lachellel** [comment]
Confirmed behavior on Chrome + Windows + mouse scroll wheel.  

It's limited to use of the scroll wheel or track pad - the focus is on the graph and the scroll makes the "graph" scroll move _in addition to_ the browser scroll.  

_It is a bit unnerving (wildly scrolling out or in) until you figure out what's happening!_

**Comment by indrajit-gsa** [comment]
It is the same behavior that existed in the older graph - https://fpki-graph.fpki-lab.gov/, just that this one has the page scroll in addition to the graph zoom because we have the horizontal scroll. The graph is zooming in/out with the mouse scroll button as expected. I will see if I can disable it, though I suspect the zoom functionality may be disabled as well.

**Comment by indrajit-gsa** [comment]
I disabled the zoom on mouse scroll for the graph. The zoom slider will allow zooming in/out of the graph. 
Here is the [preview](https://federalist-proxy.app.cloud.gov/preview/gsa/fpki-guides/fpkigraph/tools/fpkigraph/).

**Comment by lachellel** [comment]
Nice!  LGTM

**Comment by konklone** [comment]
:+1: from me as well!

**Comment by indrajit-gsa** [comment]
This issue is now resolved.
