### ISSUE TITLE
Microsoft: serverAuth Removal Testing

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#206]
#### Description of Issue: ####
- We need a common set of test procedures for testing the removal of serverAuth from the USG root (Federal Common Policy CA)
- Test procedures need to be focused on the govt intranets and domain joined (or managed) equipment
- Initial April 2018 testing will be on a alpha Certificate Trust List 
- Common root certificate will still have the serverAuth EKU and a notBeforeDate in the CTL
- Common root certificate will still be distributed in the CTL with other EKUs

#### Details of Issue: #### 
- Initial testing assumed that the Certificate Trust List and AuthRoot properties could be overridden by enterprise policies (physical or virtual stores)
- Initial testing assumed the EKU would not be distributed with the certificate in the CTL (no EKU)
- Actual implementation requires distribution of the EKU in the CTL with either a date (explicit deny) or a not permissible flag (explicit deny)
- Initial feedback has been the explicit deny options distributed in the CTL would not be able to be overridden by enterprise policies  

Other Info:
- CTL => AuthRoot => Third-party Root CAs
- GPO or Enterprise => Enterprise 

**Future plans under consideration and planning:** 
- Removing Federal Common Policy CA from Microsoft trust store program entirely

 

#### Link to the Content Page for Contributors: ####
- Use weird science patch branch?  https://github.com/GSA/fpki-guides/blob/weirdscience-patch-1/_announcements/01_microsoft_constraint.md

**Comment by lachellel** [comment]
From MSFT:  Testing is ready.  Please follow the instructions below.
 
http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/USPKI

Below steps can be used for testing:

On each test system, modify following registry key to work with the new CTL:

- [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate] "RootDirUrl"=http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/USPKI

And delete the following keys:

- [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\EncodedCtl]  [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\LastSyncTime]
- [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\Certificates] (deleting all cached certificates)

 Once testing is done, to return the systems to their normal configuration:

 On each test system, modify following registry key to work with the default URL:

- [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate] "RootDirUrl"=http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en

 And delete these keys again:

- [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\EncodedCtl]      [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\LastSyncTime]
- [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\Certificates] (deleting all cached certificates)

**Comment by lachellel** [comment]
From @weirdscience 

A couple points from Microsoft:

- A disallow is used instead of a notBefore for the first phase of testing. It allows a more reliable test than a notBefore. The next phase of testing will/may include a notBefore.
- All testing needs to happen in Windows 10 using Edge/IE.
- Results may vary when using Chrome in Windows 10 so test accordingly under different conditions. 

After you make the registry updates: 

- run certutil.exe -generateSSTFromWA command to pull everything from Windows Update.  
- You could also run the -SyncwithWU command

**Comment by weirdscience** [comment]
I'll integrate this into the announcements page. #186

**Comment by weirdscience** [comment]
_**Current Test Results Status**_  

- Microsoft set the CTL to Disallow Server Auth to Common Policy. Due to this, certificate validation it breaks to every website in IE, Edge, Chrome using Common Policy as the Root. Even if Common Policy is published using GPO to enterprise stores, we still receive validation errors.

- If there is a path to another root, then there is no validation error.  For example, if NASA distributes both Common Policy and the Treasury Root because NASA is subordinate to Treasury. The browsers seem to fail open as long as there is one good path. Doesn't matter how many bad paths as long as there is one good path.

- We have different validation results using CertUtil and the Browser. CertUtil appears to use Common Policy even if paths exist to other roots. Chrome or IE/Edge will pick whatever good path exists. CAPI seems to prefer newer, longer path information.
Make sure to clear browser cache in IE and refresh the website in Chrome after making changes. Both browsers seem to cache validation results.

**_Updated Test Use Cases_**

- Any certificate asserting Server Auth and uses CAPI should be verified.

- Windows 10 should be only impacted platform. Potential that Windows 7, Windows 8, Server 2008/2012/2016 may use CTL but they do not process the advanced notBefore or Disallowed checks.

- Websites accessed through browsers: Microsoft IE/Edge, Google Chrome

**_Tentative Test Schedule_**
4/26 - Report to Microsoft on initial Disallow Testing
4/27 - 5/2 - Remediate Disallow Testing based on Microsoft Feedback Microsoft Prep for Server Auth notBefore Testing CTL. Determine alternative options to discuss with Microsoft.
5/2 - Status Call/Email with Testers on Disallow results and/or questions
5/3 - Report to Microsoft on final Disallow testing. Discuss alternative options and next steps if more testing is needed.
5/3 - 5/16 - notBefore Testing
5/9 - Status Call/Email with Testers on notBefore results and/or questions
5/17 - Report to Microsoft on final notbefore testing. Determine next steps

Questions for Microsoft

- [x] Can Microsoft setup multiple CTLs for parallel testing? Disallow, notBefore, and no Common?
Answer: No.
- [X] What versions of Microsoft use CTL? Microsoft said Windows 10, but it seems servers, Windows 7, and 8 also use CTL?
- Answer: Windows 10 code base is the only version that processes the advanced CTL notBefore and Disallowed feature. Windows 7 and 8 code (including Server 2008 R2/2012/2016) may process a CTL if the feature is enabled but will only process a trusted or untrusted list.

- [X] Can we pick the notBefore date?
- Anwser: Yes.

- [ ] If Common Policy is removed from Microsoft, how will that be distributed? Will an update remove it or will it stop being distributed with Windows?

Questions for internal research

- [X] What is browser behavior if CTL cannot be found or CTL is turned off?
- Answer:  We recommend that administrators who manage their own list of trusted root certificates disable the Automatic Update service for trusted CTLs. However, we do not recommend that administrators disable the Automatic Update service for untrusted CTLs. 
- Link: https://support.microsoft.com/en-us/help/2813430/an-update-is-available-that-enables-administrators-to-update-trusted-a

- [X] How do we build a CTL?
- Answer: This software update introduces a new tool that administrators can use to view the set of trusted root certificates in the Microsoft Root Certificate Program. This tool is for administrators who manage the set of trusted root certificates for an enterprise environment. An administrator can use this tool to select the set of trusted root certificates, export them to a serialized certificate store, and distribute them by using Group Policy. For more information, see the New Verbs in Certutil section in this KB article. Need to verify if this works. Vague instructions on how to manually manage a set of trusted root certificates.
- Link: https://support.microsoft.com/en-us/help/2813430/an-update-is-available-that-enables-administrators-to-update-trusted-a#5 or https://msdn.microsoft.com/en-us/library/windows/desktop/aa379867(v=vs.85).aspx

- [ ] Ways to verify if CTL is an issue on certificate verification?
- Answer: Researching.....
- Link: N/A

**Comment by weirdscience** [comment]
I've incorporated all relevant information in the latest pull request #186.

**Comment by weirdscience** [comment]
@lachellel We can close this.

**Comment by weirdscience** [comment]
Testing is complete.
