### ISSUE TITLE
Where do you find all the CAs and Crawler info

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#63]

**Comment by weirdscience** [comment]
The crawler is located at fpki-graph.fpki-lab.gov. It is a graph of most FPKI CAs. I say most because it crawls down from the Common Policy Root through the SIA extension. Commercial affiliates are not required to have an SIA so some commercial CAs may not be in the crawler.

The reports page at fpki-grpah.fpki-lab.gov/crawler contains a number of csv and html reports of CAs and repo locations including a report of CDPs and different P7 configurations. 

I can add an overview to the fpki guide.

**Comment by djpackham** [comment]
For now there is a link to the FPKI graph and crawler output on the [Useful Tools](https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_tools.md) page. Is it okay if I close this @weirdscience

**Comment by lachellel** [comment]
@djpackham i would close but open another 
the crawler doesn't have a "how to use and understand" information with it
using the p7b files from the crawler without understanding how to use them or what to use - is dangerous.

**Comment by weirdscience** [comment]
Works for me.
