### ISSUE TITLE
Card Testing Common Issues Checklist

### ISSUE THREAD

**Issue by Protiviti-JSargent** [GSA/fpki-guides#74]
#### Description of Issue: ####
Create a list of common issues discovered during PIV/PIV-I card testing for agencies to use as a pre-checklist before scheduling a date for in-person testing of PIV/PIV-I cards

#### Details of Issue: ####
The checklist will be separated by issue with description of what the problem is, general guidance on how to check for the issue on their credential, and links to requirement/reference docs.

The idea is for this to be a 'living document' with new issues included as they are discovered.

#### References (Docs, Links, Files): ####
word version of doc already created, not currently posted

#### If a New Page or Content is Needed, Expected Outcomes: ####
New Page to be created

#### Link to the Content Page for Contributors: ####
pull request submitted to create \pages\PIV_Testing_Checklist.md

**Comment by Protiviti-JSargent** [comment]
@lachellel From the discussion on Friday, I believe we decided to put the Common Issues list under the PIV-guides repo.  If so, should this issue be closed out, or did I misunderstand and the issues list should go here?

**Comment by djpackham** [comment]
I can answer this one. We are keeping it under the FPKI-guides since it has
to do with the FPKI card testing.

On May 3, 2017, at 9:11 PM, Protiviti-JSargent <notifications@github.com>
wrote:

@lachellel <https://github.com/lachellel> From the discussion on Friday, I
believe we decided to put the Common Issues list under the PIV-guides repo.
If so, should this issue be closed out, or did I misunderstand and the
issues list should go here?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GSA/fpki-guides/issues/74#issuecomment-299076870>, or mute
the thread

**Comment by Protiviti-JSargent** [comment]
submitted pull request #104

**Comment by ryancdickson** [comment]
@idmken - Recommend we close this issue.  We're working on an internal document to track common PIV testing issues and resolutions, but I don't feel this is appropriate for FPKI-Guides (and perhaps public posting).

**Comment by ryancdickson** [comment]
Closing issue as we begin the migration to the new Playbook Repository.
