### ISSUE TITLE
FBCA2016 P7C appears corrupted

### ISSUE THREAD

**Issue by tridentity** [GSA/fpki-guides#793]
Went to download the p7c for the Issued By FBCA2016 and the size is only 41bytes

http://http.fpki.gov/bridge/caCertsIssuedByfbca2016.p7c

<img width="199" alt="Screen Shot 2020-12-02 at 12 49 55 PM" src="https://user-images.githubusercontent.com/43041865/100911249-f97a0c80-349c-11eb-9427-98a077bd5426.png">

**Comment by ryancdickson** [comment]
@tridentity - The Federal Bridge CA (FBCA) 2016 has been decommissioned.  The bundle is empty because there are no CAs with valid certificates issued by FBCA 2016. CAs previously cross certified by FBCA 2016 were migrated to the Federal Bridge CA G4.

Useful artifacts:


Federal Bridge CA G4 | Information
-- | --
Certificate Revocation List | http://repo.fpki.gov/bridge/fbcag4.crl
P7C file - Issued By | http://repo.fpki.gov/bridge/caCertsIssuedByfbcag4.p7c
P7C file - Issued To | http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c

**Comment by lachellel** [comment]
@tridentity @ryancdickson 

It's this page that I believe @tridentity is referring to: 

- [x] Update to remove FBCA 2016:  https://fpki.idmanagement.gov/crls/

**Comment by ryancdickson** [comment]
Merged into staging. Closing issue.
