### ISSUE TITLE
Using the FPKI Overlay

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#8]
@mattking1 is developing a playbook to explain how to use the FPKI Overlay of NIST SP 800-53

**Comment by MattKing1** [comment]
Audience: PKI Issuers

**Comment by idmken** [comment]
@maxwellfunk @ryancdickson is there a need for this?

**Comment by ryancdickson** [comment]
@idmken - I don't think this is necessary (anymore).  

1. The draft Overlay (to align with R5) now contains a "How to Use FPKI Overlay Security Controls Table" section.
2. Using the FPKI Overlay shouldn't be any different than using any other overlay. 
3. In our past working group meetings (PA) where the Overlay was discussed, I cannot recall anyone requesting this type of document.

I think we're good to close.  

Re-open if you (or @maxwellfunk) feel otherwise.
